---
- name: Configure DHCP server on blue8-fw
  hosts: blue8-fw
  tasks:
    - name: Set DHCP global local-address
      vyos.vyos.vyos_config:
        lines:
          - set service dhcp-server global-parameters "local-address 10.0.5.2"
          - set service dhcp-server shared-network-name BLUE8 authoritative
          - set service dhcp-server shared-network-name BLUE8 authoritative
          - set service dhcp-server shared-network-name BLUE8 subnet 10.0.5.0/24 default-router 10.0.5.2
          - set service dhcp-server shared-network-name BLUE8 subnet 10.0.5.0/24 domain-name blue8.local
          - set service dhcp-server shared-network-name BLUE8 subnet 10.0.5.0/24 lease 86400
          - set service dhcp-server shared-network-name BLUE8 subnet 10.0.5.0/24 name-server 10.0.5.5
          - set service dhcp-server shared-network-name BLUE8 subnet 10.0.5.0/24 range BLUE8--POOL start 10.0.5.75
          - set service dhcp-server shared-network-name BLUE8 subnet 10.0.5.0/24 range BLUE8--POOL stop 10.0.5.125
        save: true
    - name: Verify DHCP config was applied
      vyos.vyos.vyos_command:
        commands:
          - show service dhcp-server
      register: dhcp_output
