all:
  children:
    ubuntu:
      hosts:
        ubuntu-1:
          ansible_host: 10.0.5.83
          ansible_user: rangeuser
          static_ip: 10.0.5.30
        ubuntu-2:
          ansible_host: 10.0.5.84
          ansible_user: rangeuser
          static_ip: 10.0.5.31
